### ISSUE TITLE
Tags not applied to the IAM policies

### ISSUE THREAD

**Issue by jkasarherou** [symopsio/terraform-aws-runtime-connector#1]
Hello team.
the module has the `tags` variable to attach tags to resources, however the tags are not attached to the IAM policies.

**Comment by llam15** [comment]
Hi! Thanks for flagging this issue :) It has been addressed and released in [version 1.0.5 of the module](https://github.com/symopsio/terraform-aws-runtime-connector/releases/tag/v1.0.5)!
